#------------------------------
# Langs
#------------------------------
[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = '''
  set helplang=ja,en
'''
# Toml
#------------------------------
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

# Markdown
#------------------------------
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md', 'markdown']
hook_add = '''
  let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']
  autocmd BufNewFile,BufRead *.md set filetype=markdown tabstop=2 shiftwidth=2
'''
repo = 'pocke/vim-textobj-markdown'
on_ft = ['md', 'markdown']

# Web
#------------------------------

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql', 'qql', 'Relay.QL', 'js']
hook_add = """
  autocmd BufNewFile,BufRead *.graphql set tabstop=2 shiftwidth=2
"""

[[plugins]]
repo  = 'othree/html5.vim'
on_ft = ['html', 'php', 'html.twig', 'twig', 'riot']
hook_add = '''
  autocmd BufNewFile,BufRead *.html set tabstop=4 shiftwidth=4
  autocmd BufNewFile,BufRead *.twig, *.html.twig set tabstop=4 shiftwidth=4
'''

# CSS

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'
hook_add = """
"""

repo = 'stephenway/postcss.vim'
on_ft = 'postcss'
hook_add = """
"""

[[plugins]]
repo = 'gcorne/vim-sass-lint'
on_ft = ['sass', 'scss']
hook_add = '''
  autocmd BufNewFile,BufRead *.scss set filetype=scss tabstop=2 shiftwidth=2
'''

#  Javascript
#-----------------------------------

# JS syntax

[[plugins]]
repo = 'othree/yajs.vim'
depends = ['ale']
on_ft = ['javascript', 'jsx', 'javascript.jsx']
hook_add = """
  autocmd BufNewFile,BufRead *.js set filetype=javascript tabstop=2 shiftwidth=2
  autocmd BufNewFile,BufRead *.es6 set filetype=javascript tabstop=2 shiftwidth=2

  let g:ale_fixers['javascript'] = ['prettier-eslint']
  let g:ale_javascript_prettier_use_local_config = 1
"""

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'jsx', 'javascript.jsx']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'jsx', 'javascript.jsx']
hook_add = '''
  function! EnableJavascript()
    " Setup used libraries
    let g:used_javascript_libs = 'jquery,underscore,react,flux,jasmine'
    let b:javascript_lib_use_jquery = 1
    let b:javascript_lib_use_underscore = 1
    let b:javascript_lib_use_react = 1
    let b:javascript_lib_use_flux = 1
    let b:javascript_lib_use_jasmine = 1
    let b:javascript_lib_use_vue = 1
  endfunction
  autocmd FileType javascript,jsx,javascript.jsx call EnableJavascript()
'''

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['jsx', 'javascript.jsx']
hook_add = """
  autocmd BufRead,BufNewFile *.jsx set filetype=jsx.javascript tabstop=2 shiftwidth=2
"""

# utils

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'jsx', 'javascript.jsx']
hook_add = '''
  let g:js_indent_flat_switch = 1
'''

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'

# Typescript

[[plugins]] 
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.tsx']
hook_add = """
  autocmd BufRead,BufNewFile *.ts set filetype=typescript expandtab tabstop=2 shiftwidth=2

  let g:typescript_compiler_binary = 'tsc'
  let g:typescript_compiler_options = ''

  "let g:typescript_indent_disable = 1
  "let g:typescript_opfirst='\%([<>=,?^%|*/&]\|\([-:+]\)\1\@!\|!=\|in\%(stanceof\)\=\>\)'
"""

[[plugins]]
repo = 'aanari/vim-tsx-pretty'
on_ft = ['typescript', 'typescript.tsx']
hook_add = """
  autocmd BufRead,BufNewFile *.tsx set filetype=typescript expandtab tabstop=2 shiftwidth=2
"""

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript', 'typescript.tsx']
depends = ['vim-tsx-pretty', 'typescript-vim']

# linter & formatter

[[plugins]]
repo     = 'prettier/vim-prettier'
build    = 'npm install'
on_ft    = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx', 'vue', 'css', 'scss', 'json', 'markdown']
hook_source = """
  " @formatアノテーションを持ったファイルの自動フォーマットを無効にする
  let g:prettier#autoformat = 0

  " Prettierのパースエラーをquickfixに表示しない
  let g:prettier#quickfix_enabled = 0

  autocmd BufWritePre *.js,*.ts,*tsx,*.vue,*.css,*.scss,*.json,*.md PrettierAsync
"""

[[plugins]]
repo = 'fleischie/vim-styled-components'
on_ft = ['javascript', 'jsx', 'javascript.jsx', 'typescript', 'typescript.tsx']


# Ruby
#-----------------------------------

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'eruby']
hook_add = """
 autocmd BufNewFile,BufRead *.rb set tabstop=2 shiftwidth=2
 autocmd BufNewFile,BufRead *.erb set tabstop=2 shiftwidth=2
"""

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby']
hook_add = """
  autocmd FileType ruby nnoremap <silent> ,a :<C-u>A<CR><ESC>
  autocmd FileType ruby nnoremap <silent> ,at :<C-u>AT<CR><ESC>
  autocmd FileType ruby nnoremap <silent> ,av :<C-u>AV<CR><ESC>
  autocmd FileType ruby nnoremap <silent> ,as :<C-u>AS<CR><ESC>

  let g:surround_{char2nr("-")} = "<% \r %>"
  let g:surround_{char2nr("=")} = "<%= \r %>"
"""
